Repository dooboolab-community/expo-router-starter, pull requests merged in 2023-06, with the labels that each got.

#2 test: setup test env with jest
  .github/workflows/ci.yml
  __mocks__/expo-asset.ts
  __mocks__/sentry-expo.ts
  assets/langs/en.json
  assets/langs/ko.json
  jest.config.ts
  package.json
  src/providers/index.tsx
  src/uis/ListEmptyItem.tsx
  src/uis/__tests__/ListEmptyItem.test.tsx
  src/utils/error.ts
  test/testSetup.ts
  test/testSetupAfterEnv.ts
  test/testUtils.tsx
  tsconfig.json
  yarn.lock
Labels: test

#3 bugfix: modify routing structure
  app/(home)/_layout.tsx
  app/_layout.tsx
  app/details.tsx
  app/index.tsx
Labels: bug

#4 feat: dooboo-cli compatibility
  .dooboo/expo
  app.config.ts
  app/details.tsx
  app/index.tsx
  jest.config.ts
  metro.config.js
  package.json
  src/apis/sample.ts
  src/apis/urls.ts
  src/providers/ReducerProvider.tsx
  src/providers/StateProvider.tsx
  src/utils/createCtx.tsx
  test/app/details.test.tsx
  test/app/index.test.tsx
  test/src/apis/sample.test.ts
  test/src/providers/ReducerProvider.test.tsx
  test/src/providers/StateProvider.test.tsx
  test/src/uis/ListEmptyItem.test.tsx
  test/testSetup.ts
  tsconfig.json
  yarn.lock
Labels: enhancement
